name: test

on: [push]


jobs:
  build:
    runs-on: 'ubuntu-20.04'
    
    outputs:
      build_matrix: ${{ steps.set-matrix.outputs.matrix }}
      imageBuilder: ${{ steps.organize.outputs.imageBuilder }}
      build_target: ${{ steps.organize.outputs.build_target }}
    name: "编译 ${{matrix.target}}"
    strategy:
      fail-fast: false
      matrix:
        target: 
          - "[1,2,3]" # sed_for_matrix
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: prinf info
      id: set-matrix
      run: |
        echo  ${{matrix.target}}
        echo  '${{ toJson(matrix.target) }}'
        current_workflow_file_name=$(find ${GITHUB_WORKSPACE}/.github/workflows/ -type f -exec grep -Pl '^name:\s*${{ github.workflow }}' {} \;)
        
        echo "::set-output name=matrix::${{ matrix.target }}"
        
  build_slim:
    needs: build
    runs-on: 'ubuntu-20.04'
    name: "编译 ${{matrix.target}}"
    strategy:
      fail-fast: false
      matrix:
        target: ${{ needs.build.outputs.build_matrix }}
        type: [slim,""]
    steps:
    - name: prinf info
      run: |
        echo  ${{matrix.target}}
